[features]
seeds = false
[programs.localnet]
launchpad = "2Vq3XGx6PUNyczT7jNzfb3cKw4C6SAA5JfkP2H3q7hhP"
[programs.devnet]
launchpad = "2Vq3XGx6PUNyczT7jNzfb3cKw4C6SAA5JfkP2H3q7hhP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
