[features]
seeds = false
[programs.localnet]
launchpad = "73DSgY3VigDXoUK4FcD81M4YBv3GSgud7JoKDhEzaNFB"
[programs.devnet]
launchpad = "73DSgY3VigDXoUK4FcD81M4YBv3GSgud7JoKDhEzaNFB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
